// Copyright (c) 2022 Pestras
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

const tzlist = [{
  id: 1,
  continent: 'Asia',
  cities: [
    { id: 1, city: 'Dubai', tz: 'Asia/Dubai' },
    { id: 2, city: 'Kabul', tz: 'Asia/Kabul' },
    { id: 3, city: 'Yerevan', tz: 'Asia/Yerevan' },
    { id: 4, city: 'Baku', tz: 'Asia/Baku' },
    { id: 5, city: 'Dhaka', tz: 'Asia/Dhaka' },
    { id: 6, city: 'Brunei', tz: 'Asia/Brunei' },
    { id: 7, city: 'Thimphu', tz: 'Asia/Thimphu' },
    { id: 8, city: 'Shanghai', tz: 'Asia/Shanghai' },
    { id: 9, city: 'Urumqi', tz: 'Asia/Urumqi' },
    { id: 10, city: 'Nicosia', tz: 'Asia/Nicosia' },
    { id: 11, city: 'Famagusta', tz: 'Asia/Famagusta' },
    { id: 12, city: 'Tbilisi', tz: 'Asia/Tbilisi' },
    { id: 13, city: 'Hong_Kong', tz: 'Asia/Hong_Kong' },
    { id: 14, city: 'Jakarta', tz: 'Asia/Jakarta' },
    { id: 15, city: 'Pontianak', tz: 'Asia/Pontianak' },
    { id: 16, city: 'Makassar', tz: 'Asia/Makassar' },
    { id: 17, city: 'Jayapura', tz: 'Asia/Jayapura' },
    { id: 18, city: 'Jerusalem', tz: 'Asia/Jerusalem' },
    { id: 19, city: 'Kolkata', tz: 'Asia/Kolkata' },
    { id: 20, city: 'Baghdad', tz: 'Asia/Baghdad' },
    { id: 21, city: 'Tehran', tz: 'Asia/Tehran' },
    { id: 22, city: 'Amman', tz: 'Asia/Amman' },
    { id: 23, city: 'Tokyo', tz: 'Asia/Tokyo' },
    { id: 24, city: 'Bishkek', tz: 'Asia/Bishkek' },
    { id: 25, city: 'Pyongyang', tz: 'Asia/Pyongyang' },
    { id: 26, city: 'Seoul', tz: 'Asia/Seoul' },
    { id: 27, city: 'Almaty', tz: 'Asia/Almaty' },
    { id: 28, city: 'Qyzylorda', tz: 'Asia/Qyzylorda' },
    { id: 29, city: 'Qostanay', tz: 'Asia/Qostanay' },
    { id: 30, city: 'Aqtobe', tz: 'Asia/Aqtobe' },
    { id: 31, city: 'Aqtau', tz: 'Asia/Aqtau' },
    { id: 32, city: 'Atyrau', tz: 'Asia/Atyrau' },
    { id: 33, city: 'Oral', tz: 'Asia/Oral' },
    { id: 34, city: 'Beirut', tz: 'Asia/Beirut' },
    { id: 35, city: 'Colombo', tz: 'Asia/Colombo' },
    { id: 36, city: 'Yangon', tz: 'Asia/Yangon' },
    { id: 37, city: 'Ulaanbaatar', tz: 'Asia/Ulaanbaatar' },
    { id: 38, city: 'Hovd', tz: 'Asia/Hovd' },
    { id: 39, city: 'Choibalsan', tz: 'Asia/Choibalsan' },
    { id: 40, city: 'Macau', tz: 'Asia/Macau' },
    { id: 41, city: 'Kuala_Lumpur', tz: 'Asia/Kuala_Lumpur' },
    { id: 42, city: 'Kuching', tz: 'Asia/Kuching' },
    { id: 43, city: 'Karachi', tz: 'Asia/Karachi' },
    { id: 44, city: 'Gaza', tz: 'Asia/Gaza' },
    { id: 45, city: 'Hebron', tz: 'Asia/Hebron' },
    { id: 46, city: 'Kathmandu', tz: 'Asia/Kathmandu' },
    { id: 47, city: 'Yekaterinburg', tz: 'Asia/Yekaterinburg' },
    { id: 48, city: 'Qatar', tz: 'Asia/Qatar' },
    { id: 49, city: 'Omsk', tz: 'Asia/Omsk' },
    { id: 50, city: 'Novosibirsk', tz: 'Asia/Novosibirsk' },
    { id: 51, city: 'Barnaul', tz: 'Asia/Barnaul' },
    { id: 52, city: 'Tomsk', tz: 'Asia/Tomsk' },
    { id: 53, city: 'Novokuznetsk', tz: 'Asia/Novokuznetsk' },
    { id: 54, city: 'Krasnoyarsk', tz: 'Asia/Krasnoyarsk' },
    { id: 55, city: 'Irkutsk', tz: 'Asia/Irkutsk' },
    { id: 56, city: 'Chita', tz: 'Asia/Chita' },
    { id: 57, city: 'Yakutsk', tz: 'Asia/Yakutsk' },
    { id: 58, city: 'Khandyga', tz: 'Asia/Khandyga' },
    { id: 59, city: 'Vladivostok', tz: 'Asia/Vladivostok' },
    { id: 60, city: 'Ust-Nera', tz: 'Asia/Ust-Nera' },
    { id: 61, city: 'Singapore', tz: 'Asia/Singapore' },
    { id: 62, city: 'Magadan', tz: 'Asia/Magadan' },
    { id: 63, city: 'Sakhalin', tz: 'Asia/Sakhalin' },
    { id: 64, city: 'Srednekolymsk', tz: 'Asia/Srednekolymsk' },
    { id: 65, city: 'Kamchatka', tz: 'Asia/Kamchatka' },
    { id: 66, city: 'Anadyr', tz: 'Asia/Anadyr' },
    { id: 67, city: 'Bangkok', tz: 'Asia/Bangkok' },
    { id: 68, city: 'Dushanbe', tz: 'Asia/Dushanbe' },
    { id: 69, city: 'Taipei', tz: 'Asia/Taipei' },
    { id: 70, city: 'Dili', tz: 'Asia/Dili' },
    { id: 71, city: 'Ashgabat', tz: 'Asia/Ashgabat' },
    { id: 72, city: 'Damascus', tz: 'Asia/Damascus' },
    { id: 73, city: 'Riyadh', tz: 'Asia/Riyadh' },
    { id: 74, city: 'Samarkand', tz: 'Asia/Samarkand' },
    { id: 75, city: 'Tashkent', tz: 'Asia/Tashkent' },
    { id: 76, city: 'Ho_Chi_Minh', tz: 'Asia/Ho_Chi_Minh' },
  ],
},
{
  id: 2,
  continent: 'Europe',
  cities: [
    { id: 1, city: 'Andorra', tz: 'Europe/Andorra' },
    { id: 2, city: 'Tirane', tz: 'Europe/Tirane' },
    { id: 3, city: 'Vienna', tz: 'Europe/Vienna' },
    { id: 4, city: 'Brussels', tz: 'Europe/Brussels' },
    { id: 5, city: 'Sofia', tz: 'Europe/Sofia' },
    { id: 6, city: 'Minsk', tz: 'Europe/Minsk' },
    { id: 7, city: 'Zurich', tz: 'Europe/Zurich' },
    { id: 8, city: 'Prague', tz: 'Europe/Prague' },
    { id: 9, city: 'Berlin', tz: 'Europe/Berlin' },
    { id: 10, city: 'Copenhagen', tz: 'Europe/Copenhagen' },
    { id: 11, city: 'Tallinn', tz: 'Europe/Tallinn' },
    { id: 12, city: 'Madrid', tz: 'Europe/Madrid' },
    { id: 13, city: 'Helsinki', tz: 'Europe/Helsinki' },
    { id: 14, city: 'Paris', tz: 'Europe/Paris' },
    { id: 15, city: 'London', tz: 'Europe/London' },
    { id: 16, city: 'Gibraltar', tz: 'Europe/Gibraltar' },
    { id: 17, city: 'Athens', tz: 'Europe/Athens' },
    { id: 18, city: 'Budapest', tz: 'Europe/Budapest' },
    { id: 19, city: 'Dublin', tz: 'Europe/Dublin' },
    { id: 20, city: 'Rome', tz: 'Europe/Rome' },
    { id: 21, city: 'Vilnius', tz: 'Europe/Vilnius' },
    { id: 22, city: 'Luxembourg', tz: 'Europe/Luxembourg' },
    { id: 23, city: 'Riga', tz: 'Europe/Riga' },
    { id: 24, city: 'Monaco', tz: 'Europe/Monaco' },
    { id: 25, city: 'Chisinau', tz: 'Europe/Chisinau' },
    { id: 26, city: 'Malta', tz: 'Europe/Malta' },
    { id: 27, city: 'Amsterdam', tz: 'Europe/Amsterdam' },
    { id: 28, city: 'Oslo', tz: 'Europe/Oslo' },
    { id: 29, city: 'Warsaw', tz: 'Europe/Warsaw' },
    { id: 30, city: 'Warsaw', tz: 'Europe/Warsaw' },
    { id: 31, city: 'Lisbon', tz: 'Europe/Lisbon' },
    { id: 32, city: 'Bucharest', tz: 'Europe/Bucharest' },
    { id: 33, city: 'Belgrade', tz: 'Europe/Belgrade' },
    { id: 34, city: 'Kaliningrad', tz: 'Europe/Kaliningrad' },
    { id: 35, city: 'Moscow', tz: 'Europe/Moscow' },
    { id: 36, city: 'Simferopol', tz: 'Europe/Simferopol' },
    { id: 37, city: 'Kirov', tz: 'Europe/Kirov' },
    { id: 38, city: 'Astrakhan', tz: 'Europe/Astrakhan' },
    { id: 39, city: 'Volgograd', tz: 'Europe/Volgograd' },
    { id: 40, city: 'Saratov', tz: 'Europe/Saratov' },
    { id: 41, city: 'Ulyanovsk', tz: 'Europe/Ulyanovsk' },
    { id: 42, city: 'Samara', tz: 'Europe/Samara' },
    { id: 43, city: 'Stockholm', tz: 'Europe/Stockholm' },
    { id: 44, city: 'Istanbul', tz: 'Europe/Istanbul' },
    { id: 45, city: 'Kiev', tz: 'Europe/Kiev' },
    { id: 46, city: 'Uzhgorod', tz: 'Europe/Uzhgorod' },
    { id: 47, city: 'Zaporozhye', tz: 'Europe/Zaporozhye' },
  ],
},
{
  id: 3,
  continent: 'Antarctica',
  cities: [
    { id: 1, city: 'Casey', tz: 'Antarctica/Casey' },
    { id: 2, city: 'Davis', tz: 'Antarctica/Davis' },
    { id: 3, city: 'DumontDUrville', tz: 'Antarctica/DumontDUrville' },
    { id: 4, city: 'Mawson', tz: 'Antarctica/Mawson' },
    { id: 5, city: 'Palmer', tz: 'Antarctica/Palmer' },
    { id: 6, city: 'Rothera', tz: 'Antarctica/Rothera' },
    { id: 7, city: 'Syowa', tz: 'Antarctica/Syowa' },
    { id: 8, city: 'Troll', tz: 'Antarctica/Troll' },
    { id: 9, city: 'Vostok', tz: 'Antarctica/Vostok' },
    { id: 10, city: 'Macquarie', tz: 'Antarctica/Macquarie' },
  ],
},
{
  id: 4,
  continent: 'America',
  cities: [
    { id: 1, city: 'Buenos_Aires', tz: 'America/Argentina/Buenos_Aires' },
    { id: 2, city: 'Cordoba', tz: 'America/Argentina/Cordoba' },
    { id: 3, city: 'Salta', tz: 'America/Argentina/Salta' },
    { id: 4, city: 'Jujuy', tz: 'America/Argentina/Jujuy' },
    { id: 5, city: 'Tucuman', tz: 'America/Argentina/Tucuman' },
    { id: 6, city: 'Catamarca', tz: 'America/Argentina/Catamarca' },
    { id: 7, city: 'La_Rioja', tz: 'America/Argentina/La_Rioja' },
    { id: 8, city: 'San_Juan', tz: 'America/Argentina/San_Juan' },
    { id: 9, city: 'Mendoza', tz: 'America/Argentina/Mendoza' },
    { id: 10, city: 'San_Luis', tz: 'America/Argentina/San_Luis' },
    { id: 11, city: 'Rio_Gallegos', tz: 'America/Argentina/Rio_Gallegos' },
    { id: 12, city: 'Ushuaia', tz: 'America/Argentina/Ushuaia' },
    { id: 13, city: 'Barbados', tz: 'America/Barbados' },
    { id: 14, city: 'La_Paz', tz: 'America/La_Paz' },
    { id: 15, city: 'Belem', tz: 'America/Belem' },
    { id: 16, city: 'Fortaleza', tz: 'America/Fortaleza' },
    { id: 17, city: 'Recife', tz: 'America/Recife' },
    { id: 18, city: 'Araguaina', tz: 'America/Araguaina' },
    { id: 19, city: 'Maceio', tz: 'America/Maceio' },
    { id: 20, city: 'Bahia', tz: 'America/Bahia' },
    { id: 21, city: 'Sao_Paulo', tz: 'America/Sao_Paulo' },
    { id: 22, city: 'Campo_Grande', tz: 'America/Campo_Grande' },
    { id: 23, city: 'Cuiaba', tz: 'America/Cuiaba' },
    { id: 24, city: 'Porto_Velho', tz: 'America/Porto_Velho' },
    { id: 25, city: 'Boa_Vista', tz: 'America/Boa_Vista' },
    { id: 26, city: 'Manaus', tz: 'America/Manaus' },
    { id: 27, city: 'Eirunepe', tz: 'America/Eirunepe' },
    { id: 28, city: 'Rio_Branco', tz: 'America/Rio_Branco' },
    { id: 29, city: 'Nassau', tz: 'America/Nassau' },
    { id: 30, city: 'Belize', tz: 'America/Belize' },
    { id: 31, city: 'St_Johns', tz: 'America/St_Johns' },
    { id: 32, city: 'Halifax', tz: 'America/Halifax' },
    { id: 33, city: 'Glace_Bay', tz: 'America/Glace_Bay' },
    { id: 34, city: 'Moncton', tz: 'America/Moncton' },
    { id: 35, city: 'Goose_Bay', tz: 'America/Goose_Bay' },
    { id: 36, city: 'Blanc-Sablon', tz: 'America/Blanc-Sablon' },
    { id: 37, city: 'Toronto', tz: 'America/Toronto' },
    { id: 38, city: 'Nipigon', tz: 'America/Nipigon' },
    { id: 39, city: 'Thunder_Bay', tz: 'America/Thunder_Bay' },
    { id: 40, city: 'Iqaluit', tz: 'America/Iqaluit' },
    { id: 41, city: 'Pangnirtung', tz: 'America/Pangnirtung' },
    { id: 42, city: 'Atikokan', tz: 'America/Atikokan' },
    { id: 43, city: 'Winnipeg', tz: 'America/Winnipeg' },
    { id: 44, city: 'Rainy_River', tz: 'America/Rainy_River' },
    { id: 45, city: 'Resolute', tz: 'America/Resolute' },
    { id: 46, city: 'Rankin_Inlet', tz: 'America/Rankin_Inlet' },
    { id: 47, city: 'Regina', tz: 'America/Regina' },
    { id: 48, city: 'Swift_Current', tz: 'America/Swift_Current' },
    { id: 49, city: 'Edmonton', tz: 'America/Edmonton' },
    { id: 50, city: 'Cambridge_Bay', tz: 'America/Cambridge_Bay' },
    { id: 51, city: 'Yellowknife', tz: 'America/Yellowknife' },
    { id: 52, city: 'Inuvik', tz: 'America/Inuvik' },
    { id: 53, city: 'Creston', tz: 'America/Creston' },
    { id: 54, city: 'Dawson_Creek', tz: 'America/Dawson_Creek' },
    { id: 55, city: 'Fort_Nelson', tz: 'America/Fort_Nelson' },
    { id: 56, city: 'Vancouver', tz: 'America/Vancouver' },
    { id: 57, city: 'Whitehorse', tz: 'America/Whitehorse' },
    { id: 58, city: 'Dawson', tz: 'America/Dawson' },
    { id: 59, city: 'Santiago', tz: 'America/Santiago' },
    { id: 60, city: 'Punta_Arenas', tz: 'America/Punta_Arenas' },
    { id: 61, city: 'Bogota', tz: 'America/Bogota' },
    { id: 62, city: 'Costa_Rica', tz: 'America/Costa_Rica' },
    { id: 63, city: 'Havana', tz: 'America/Havana' },
    { id: 64, city: 'Curacao', tz: 'America/Curacao' },
    { id: 65, city: 'Santo_Domingo', tz: 'America/Santo_Domingo' },
    { id: 66, city: 'Guayaquil', tz: 'America/Guayaquil' },
    { id: 67, city: 'Cayenne', tz: 'America/Cayenne' },
    { id: 68, city: 'Godthab', tz: 'America/Godthab' },
    { id: 69, city: 'Danmarkshavn', tz: 'America/Danmarkshavn' },
    { id: 70, city: 'Scoresbysund', tz: 'America/Scoresbysund' },
    { id: 71, city: 'Cayenne', tz: 'America/Cayenne' },
    { id: 72, city: 'Godthab', tz: 'America/Godthab' },
    { id: 73, city: 'Danmarkshavn', tz: 'America/Danmarkshavn' },
    { id: 74, city: 'Scoresbysund', tz: 'America/Scoresbysund' },
    { id: 75, city: 'Thule', tz: 'America/Thule' },
    { id: 76, city: 'Guatemala', tz: 'America/Guatemala' },
    { id: 77, city: 'Guyana', tz: 'America/Guyana' },
    { id: 78, city: 'Tegucigalpa', tz: 'America/Tegucigalpa' },
    { id: 79, city: 'Port-au-Prince', tz: 'America/Port-au-Prince' },
    { id: 80, city: 'Jamaica', tz: 'America/Jamaica' },
    { id: 81, city: 'Martinique', tz: 'America/Martinique' },
    { id: 82, city: 'Mexico_City', tz: 'America/Mexico_City' },
    { id: 83, city: 'Cancun', tz: 'America/Cancun' },
    { id: 84, city: 'Merida', tz: 'America/Merida' },
    { id: 85, city: 'Monterrey', tz: 'America/Monterrey' },
    { id: 86, city: 'Matamoros', tz: 'America/Matamoros' },
    { id: 87, city: 'Caracas', tz: 'America/Caracas' },
    { id: 88, city: 'Mazatlan', tz: 'America/Mazatlan' },
    { id: 89, city: 'Chihuahua', tz: 'America/Chihuahua' },
    { id: 90, city: 'Ojinaga', tz: 'America/Ojinaga' },
    { id: 91, city: 'Hermosillo', tz: 'America/Hermosillo' },
    { id: 92, city: 'Tijuana', tz: 'America/Tijuana' },
    { id: 93, city: 'Bahia_Banderas', tz: 'America/Bahia_Banderas' },
    { id: 94, city: 'Managua', tz: 'America/Managua' },
    { id: 95, city: 'Panama', tz: 'America/Panama' },
    { id: 96, city: 'Lima', tz: 'America/Lima' },
    { id: 97, city: 'Miquelon', tz: 'America/Miquelon' },
    { id: 98, city: 'Puerto_Rico', tz: 'America/Puerto_Rico' },
    { id: 99, city: 'El_Salvador', tz: 'America/El_Salvador' },
    { id: 100, city: 'Grand_Turk', tz: 'America/Grand_Turk' },
    { id: 101, city: 'Paramaribo', tz: 'America/Paramaribo' },
    { id: 102, city: 'Asuncion', tz: 'America/Asuncion' },
    { id: 103, city: 'Port_of_Spain', tz: 'America/Port_of_Spain' },
    { id: 104, city: 'New_York', tz: 'America/New_York' },
    { id: 105, city: 'Detroit', tz: 'America/Detroit' },
    { id: 106, city: 'Louisville', tz: 'America/Kentucky/Louisville' },
    { id: 107, city: 'Monticello', tz: 'America/Kentucky/Monticello' },
    { id: 108, city: 'Indianapolis', tz: 'America/Indiana/Indianapolis' },
    { id: 109, city: 'Vincennes', tz: 'America/Indiana/Vincennes' },
    { id: 110, city: 'Winamac', tz: 'America/Indiana/Winamac' },
    { id: 111, city: 'Marengo', tz: 'America/Indiana/Marengo' },
    { id: 112, city: 'Petersburg', tz: 'America/Indiana/Petersburg' },
    { id: 113, city: 'Vevay', tz: 'America/Indiana/Vevay' },
    { id: 114, city: 'Tell_City', tz: 'America/Indiana/Tell_City' },
    { id: 115, city: 'Knox', tz: 'America/Indiana/Knox' },
    { id: 116, city: 'Chicago', tz: 'America/Chicago' },
    { id: 117, city: 'Menominee', tz: 'America/Menominee' },
    { id: 118, city: 'Denver', tz: 'America/Denver' },
    { id: 119, city: 'Boise', tz: 'America/Boise' },
    { id: 120, city: 'Phoenix', tz: 'America/Phoenix' },
    { id: 121, city: 'Center', tz: 'America/North_Dakota/Center' },
    { id: 122, city: 'New_Salem', tz: 'America/North_Dakota/New_Salem' },
    { id: 123, city: 'Beulah', tz: 'America/North_Dakota/Beulah' },
    { id: 124, city: 'Los_Angeles', tz: 'America/Los_Angeles' },
    { id: 125, city: 'Anchorage', tz: 'America/Anchorage' },
    { id: 126, city: 'Juneau', tz: 'America/Juneau' },
    { id: 127, city: 'Sitka', tz: 'America/Sitka' },
    { id: 128, city: 'Metlakatla', tz: 'America/Metlakatla' },
    { id: 129, city: 'Yakutat', tz: 'America/Yakutat' },
    { id: 130, city: 'Nome', tz: 'America/Nome' },
    { id: 131, city: 'Adak', tz: 'America/Adak' },
    { id: 132, city: 'Montevideo', tz: 'America/Montevideo' },
  ],
},
{
  id: 5,
  continent: 'Pacific',
  cities: [
    { id: 1, city: 'Pago_Pago', tz: 'Pacific/Pago_Pago' },
    { id: 2, city: 'Rarotonga', tz: 'Pacific/Rarotonga' },
    { id: 3, city: 'Easter', tz: 'Pacific/Easter' },
    { id: 4, city: 'Galapagos', tz: 'Pacific/Galapagos' },
    { id: 5, city: 'Fiji', tz: 'Pacific/Fiji' },
    { id: 6, city: 'Chuuk', tz: 'Pacific/Chuuk' },
    { id: 7, city: 'Pohnpei', tz: 'Pacific/Pohnpei' },
    { id: 8, city: 'Kosrae', tz: 'Pacific/Kosrae' },
    { id: 9, city: 'Guam', tz: 'Pacific/Guam' },
    { id: 10, city: 'Majuro', tz: 'Pacific/Majuro' },
    { id: 11, city: 'Kwajalein', tz: 'Pacific/Kwajalein' },
    { id: 12, city: 'Tarawa', tz: 'Pacific/Tarawa' },
    { id: 13, city: 'Enderbury', tz: 'Pacific/Enderbury' },
    { id: 14, city: 'Kiritimati', tz: 'Pacific/Kiritimati' },
    { id: 15, city: 'Noumea', tz: 'Pacific/Noumea' },
    { id: 16, city: 'Norfolk', tz: 'Pacific/Norfolk' },
    { id: 17, city: 'Nauru', tz: 'Pacific/Nauru' },
    { id: 18, city: 'Niue', tz: 'Pacific/Niue' },
    { id: 19, city: 'Auckland', tz: 'Pacific/Auckland' },
    { id: 20, city: 'Chatham', tz: 'Pacific/Chatham' },
    { id: 21, city: 'Tahiti', tz: 'Pacific/Tahiti' },
    { id: 22, city: 'Marquesas', tz: 'Pacific/Marquesas' },
    { id: 23, city: 'Gambier', tz: 'Pacific/Gambier' },
    { id: 24, city: 'Port_Moresby', tz: 'Pacific/Port_Moresby' },
    { id: 25, city: 'Bougainville', tz: 'Pacific/Bougainville' },
    { id: 26, city: 'Pitcairn', tz: 'Pacific/Pitcairn' },
    { id: 27, city: 'Palau', tz: 'Pacific/Palau' },
    { id: 28, city: 'Guadalcanal', tz: 'Pacific/Guadalcanal' },
    { id: 29, city: 'Fakaofo', tz: 'Pacific/Fakaofo' },
    { id: 30, city: 'Tongatapu', tz: 'Pacific/Tongatapu' },
    { id: 31, city: 'Funafuti', tz: 'Pacific/Funafuti' },
    { id: 32, city: 'Wake', tz: 'Pacific/Wake' },
    { id: 33, city: 'Honolulu', tz: 'Pacific/Honolulu' },
    { id: 34, city: 'Efate', tz: 'Pacific/Efate' },
    { id: 35, city: 'Wallis', tz: 'Pacific/Wallis' },
    { id: 36, city: 'Apia', tz: 'Pacific/Apia' },
  ],
},
{
  id: 6,
  continent: 'Australia',
  cities: [
    { id: 1, city: 'Lord_Howe', tz: 'Australia/Lord_Howe' },
    { id: 2, city: 'Hobart', tz: 'Australia/Hobart' },
    { id: 3, city: 'Currie', tz: 'Australia/Currie' },
    { id: 4, city: 'Melbourne', tz: 'Australia/Melbourne' },
    { id: 5, city: 'Sydney', tz: 'Australia/Sydney' },
    { id: 6, city: 'Broken_Hill', tz: 'Australia/Broken_Hill' },
    { id: 7, city: 'Brisbane', tz: 'Australia/Brisbane' },
    { id: 8, city: 'Lindeman', tz: 'Australia/Lindeman' },
    { id: 9, city: 'Adelaide', tz: 'Australia/Adelaide' },
    { id: 10, city: 'Darwin', tz: 'Australia/Darwin' },
    { id: 11, city: 'Perth', tz: 'Australia/Perth' },
    { id: 12, city: 'Eucla', tz: 'Australia/Eucla' },
  ],
},
{
  id: 7,
  continent: 'Africa',
  cities: [
    { id: 1, city: 'Abidjan', tz: 'Africa/Abidjan' },
    { id: 2, city: 'Algiers', tz: 'Africa/Algiers' },
    { id: 3, city: 'Cairo', tz: 'Africa/Cairo' },
    { id: 4, city: 'El_Aaiun', tz: 'Africa/El_Aaiun' },
    { id: 5, city: 'Ceuta', tz: 'Africa/Ceuta' },
    { id: 6, city: 'Accra', tz: 'Africa/Accra' },
    { id: 7, city: 'Bissau', tz: 'Africa/Bissau' },
    { id: 8, city: 'Nairobi', tz: 'Africa/Nairobi' },
    { id: 9, city: 'Monrovia', tz: 'Africa/Monrovia' },
    { id: 10, city: 'Tripoli', tz: 'Africa/Tripoli' },
    { id: 11, city: 'Casablanca', tz: 'Africa/Casablanca' },
    { id: 12, city: 'Maputo', tz: 'Africa/Maputo' },
    { id: 13, city: 'Windhoek', tz: 'Africa/Windhoek' },
    { id: 14, city: 'Lagos', tz: 'Africa/Lagos' },
    { id: 15, city: 'Khartoum', tz: 'Africa/Khartoum' },
    { id: 16, city: 'Juba', tz: 'Africa/Juba' },
    { id: 17, city: 'Sao_Tome', tz: 'Africa/Sao_Tome' },
    { id: 18, city: 'Ndjamena', tz: 'Africa/Ndjamena' },
    { id: 19, city: 'Tunis', tz: 'Africa/Tunis' },
    { id: 20, city: 'Johannesburg', tz: 'Africa/Johannesburg' },
  ],
},
{
  id: 8,
  continent: 'Atlantic',
  cities: [
    { id: 1, city: 'Azores', tz: 'Atlantic/Azores' },
    { id: 2, city: 'Bermuda', tz: 'Atlantic/Bermuda' },
    { id: 3, city: 'Madeira', tz: 'Atlantic/Madeira' },
  ],
},
{
  id: 9,
  continent: 'Atlantic',
  cities: [
    { id: 1, city: 'Cape_Verde', tz: 'Atlantic/Cape_Verde' },
    { id: 2, city: 'Canary', tz: 'Atlantic/Canary' },
    { id: 3, city: 'Stanley', tz: 'Atlantic/Stanley' },
    { id: 4, city: 'Faroe', tz: 'Atlantic/Faroe' },
    { id: 5, city: 'South_Georgia', tz: 'Atlantic/South_Georgia' },
    { id: 6, city: 'Reykjavik', tz: 'Atlantic/Reykjavik' },
  ],
},
{
  id: 10,
  continent: 'Indian',
  cities: [
    { id: 1, city: 'Cocos', tz: 'Indian/Cocos' },
    { id: 2, city: 'Christmas', tz: 'Indian/Christmas' },
    { id: 3, city: 'Chagos', tz: 'Indian/Chagos' },
    { id: 4, city: 'Mauritius', tz: 'Indian/Mauritius' },
    { id: 5, city: 'Maldives', tz: 'Indian/Maldives' },
    { id: 6, city: 'Mahe', tz: 'Indian/Mahe' },
    { id: 7, city: 'Reunion', tz: 'Indian/Reunion' },
    { id: 8, city: 'Kerguelen', tz: 'Indian/Kerguelen' },
  ],
}];

export function gettzName(city: string): string
export function gettzName(continent: string, city: string): string
export function gettzName(continent: string, city?: string): string {

  if (!!city)
    return tzlist.find(entry => entry.continent === continent)?.cities.find(entry => entry.city === city)?.tz;

  for (const entry of tzlist)
    for (const item of entry.cities)
      if (item.city === continent)
        return item.tz;

  return null;
}

export function gettzOffset(tz = Intl.DateTimeFormat().resolvedOptions().timeZone) {
  const ts_h_m = new Date().toLocaleString("en-US", {
    timeZone: tz,
    timeZoneName: 'short'
  }).split('GMT')[1];

  const sign = ts_h_m[0] === '+' ? 1 : -1;
  const [h, m] = ts_h_m.slice(1).split(':');

  return {
    milliseconds: (sign * (+h * 3600) + (!!m ? +m * 60 : 0)) * 1000,
    string: ts_h_m
  }
}

export function getCityTzOffset(city: string): any
export function getCityTzOffset(continent: string, city: string): any
export function getCityTzOffset(continent: string, city?: string): any {
  const tzname = gettzName(continent, city);

  return !!tzname ? gettzOffset(tzname) : null;
}